name: pymks
channels:
  - conda-forge
dependencies:
  - python=3.7
  - sfepy
  - scipy
  - dask
  - scikit-learn
  - toolz
  - coverage
  - matplotlib=3.1
  - numpy
  - pytest
  - pytest-cov
  - notebook
  - dask-ml
  - nbval
  - graphviz
  - python-graphviz
  - Deprecated
  - cython
